import React from "react"
import { Footer } from "./Footers"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Footer,
  "https://www.figma.com/design/SvE96xYQS7mTYMuCe41IvZ/Simple-Design-System-(Community)?node-id=321%3A11357",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <Footer />,
  },
)
