import React from "react"
import { Avatar } from "./Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/SvE96xYQS7mTYMuCe41IvZ/Simple-Design-System-(Community)?node-id=9762%3A1103",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      square: figma.enum("Shape", {
        Square: true,
      }),
      initials: figma.string("Initials"),
      alt: figma.string("Initials"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      // No matching props could be found for these Figma properties:
      // "initials": figma.string('Initials'),
      // "type": figma.enum('Type', {
      //   "Initial": "initial",
      //   "Image": "image"
      // })
    },
    example: (props) => (
      <Avatar
        square={props.square}
        initials={props.initials}
        alt={props.alt}
        size={props.size}
      />
    ),
  },
)
