import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/SvE96xYQS7mTYMuCe41IvZ/Simple-Design-System-(Community)?node-id=9762%3A426",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      // No matching props could be found for these Figma properties:
      // "hasIconStart": figma.boolean('Has Icon Start'),
      // "iconStart": figma.instance('Icon Start'),
      // "hasIconEnd": figma.boolean('Has Icon End'),
      // "iconEnd": figma.instance('Icon End'),
      // "label": figma.string('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => <Button size={props.size} variant={props.variant} />,
  },
)
