import React from "react"
import { Card } from "./Cards"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/SvE96xYQS7mTYMuCe41IvZ/Simple-Design-System-(Community)?node-id=2142%3A11380",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      direction: figma.enum("Direction", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
      variant: figma.enum("Variant", {
        Default: "default",
        Stroke: "stroke",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      // "body": figma.string('Body'),
      // "heading": figma.string('Heading'),
      // "button": figma.boolean('Button'),
      // "asset": figma.boolean('Asset'),
      // "assetType": figma.enum('Asset Type', {
      //   "Icon": "icon",
      //   "Image": "image"
      // })
    },
    example: (props) => (
      <Card direction={props.direction} variant={props.variant} />
    ),
  },
)
